### ISSUE TITLE
Cannot Install the clipkit 

### ISSUE THREAD

**Issue by zhangwenda0518** [JLSteenwyk/ClipKIT#46]
Hello teacher, 
I encountered a problem during installation.
I tried Conda or the source code but encountered the following error. Can you help me see why
my python was 3.8

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from clipkit.version import __version__
  File "/home/zhangwenda/biosoft/tree/ClipKIT/clipkit/__init__.py", line 1, in <module>
    from .api import clipkit
  File "/home/zhangwenda/biosoft/tree/ClipKIT/clipkit/api.py", line 4, in <module>
    from .clipkit import run
  File "/home/zhangwenda/biosoft/tree/ClipKIT/clipkit/clipkit.py", line 9, in <module>
    from .args_processing import process_args
  File "/home/zhangwenda/biosoft/tree/ClipKIT/clipkit/args_processing.py", line 5, in <module>
    from .helpers import SeqType
  File "/home/zhangwenda/biosoft/tree/ClipKIT/clipkit/helpers.py", line 6, in <module>
    from .msa import MSA
  File "/home/zhangwenda/biosoft/tree/ClipKIT/clipkit/msa.py", line 16, in <module>
    class MSA:
  File "/home/zhangwenda/biosoft/tree/ClipKIT/clipkit/msa.py", line 96, in MSA
    def is_any_entry_sequence_only_gaps(self) -> tuple[bool, Union[str, None]]:
TypeError: 'type' object is not subscriptable

**Comment by JLSteenwyk** [comment]
Hi @zhangwenda0518,

Thank you for choosing ClipKIT and for writing us regarding your issue.

As of ClipKIT v2.0.0, Python v3.8 is no longer supported. Python v3.8 is no longer supported because the end-of-life of v3.8 is fast approaching. Thus, we recommend updating your Python version to v3.9 or v3.10, which ClipKIT currently supports.

An alternative, but less desirable, solution is to install the last version of ClipKIT that supported Python v3.8 using the following command for installing via PIP: `pip install clipkit==1.4.1`.

ClipKIT v1.4.1 has some known (minor) bugs and lacks the complete set of features that are currently in production. Accordingly, we strongly recommend updating the Python version instead of rolling back to ClipKIT v1.4.1.

Thanks again for choosing ClipKIT for your alignment trimming needs. If ClipKIT interests you, please check out our other [software](https://jlsteenwyk.com/software.html) that may be useful!

All the best,

Jacob
