### ISSUE TITLE
[YYYY-MM-DD]: [BUG TITLE] cannot read phylip or maf files

### ISSUE THREAD

**Issue by aebaci** [JLSteenwyk/ClipKIT#59]
### Bug Summary
I have a large alignment file of CDS (248 Mb in maf format and 238 Mb in phylip format). I need to remove gaps for using it in codeml, but I get an error with both.
If I don't specify the format, the error is the following: 
(venv) (base) antonella@obelix:~/proteins_decont/CDS/fixedCDS$ clipkit output_alignmentwnnA.phy
Format type could not be read.
Please check acceptable input file formats: fasta, clustal, maf, mauve, phylip, phylip_sequential, phylip_relaxed, stockholm
Traceback (most recent call last):
  File "/home/antonella/venv/bin/clipkit", line 8, in <module>
    sys.exit(main())
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 220, in main
    execute(**process_args(args))
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 166, in execute
    trim_run, stats = run(
TypeError: cannot unpack non-iterable NoneType object

(venv) (base) antonella@obelix:~/proteins_decont/CDS/fixedCDS$ clipkit output_alignmentwnnA.phy -if phylip -co -s nt -l
Traceback (most recent call last):
  File "/home/antonella/venv/bin/clipkit", line 8, in <module>
    sys.exit(main())
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 220, in main
    execute(**process_args(args))
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 166, in execute
    trim_run, stats = run(
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 82, in run
    alignment, input_file_format = get_alignment_and_format(
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/files.py", line 32, in get_alignment_and_format
    alignment = AlignIO.read(open(input_file_name), file_format.value)
  File "/home/antonella/venv/lib/python3.9/site-packages/Bio/AlignIO/__init__.py", line 389, in read
    raise ValueError("More than one record found in handle")
ValueError: More than one record found in handle

(venv) (base) antonella@obelix:~/proteins_decont/CDS/fixedCDS$ clipkit CDSsfinaleswnamenA.maf -if maf -co -s nt -l
Traceback (most recent call last):
  File "/home/antonella/venv/bin/clipkit", line 8, in <module>
    sys.exit(main())
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 220, in main
    execute(**process_args(args))
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 166, in execute
    trim_run, stats = run(
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/clipkit.py", line 82, in run
    alignment, input_file_format = get_alignment_and_format(
  File "/home/antonella/venv/lib/python3.9/site-packages/clipkit/files.py", line 32, in get_alignment_and_format
    alignment = AlignIO.read(open(input_file_name), file_format.value)
  File "/home/antonella/venv/lib/python3.9/site-packages/Bio/AlignIO/__init__.py", line 389, in read
    raise ValueError("More than one record found in handle")
ValueError: More than one record found in handle

### Technical Details
* Python version: Run `python --version`.
Python 3.9.19
* ClipKIT version: Run `clipkit -v`
clipkit 2.3.0

**Comment by JLSteenwyk** [comment]
Hi @aebaci,

Thank you for bringing this issue to our attention. We apologize for the inconvenience.

To facilitate resolving this issue, would you be willing to share your input files?

Please feel free to send them an email if you'd like [https://jlsteenwyk.com/contact.html](https://jlsteenwyk.com/contact.html). 

Best,

Jacob

**Comment by JLSteenwyk** [comment]
Hi @aebaci,

Thank you for sending the file via email.

I looked at the input file and noticed that multiple alignment files have been concatenated together (specifically, it looks like the input was generated using something like this command: `cat single_gene_alignments* > msa.file`).

The input of ClipKIT is a single multiple sequence alignment file at a time; e.g., `clipkit single_gene_alignment`.

If there is any other confusion, please let me know and I would be happy to help you further.

Cheers,

Jacob
